#!/bin/bash
set -eu -o pipefail

die() {
  printf '"%s" ' Error: "$@" 1>&2
  echo "" 1>&2
  exit 1
}

fail-if() {
  "${@:2}" &> /dev/null ||
    die "$1": "${@:2}"
}

equals() {
  [ "$1" = "$2" ] &&
    return 0
  return 1
}

ORIG_PWD="$(pwd)"
TMP="$(mktemp -d /tmp/srepoXXXXXXXXX)"
cleanup() {
  # Ensure we're not in $TMP
  cd "$ORIG_PWD"
  rm -rf "$TMP"
}
trap cleanup INT TERM EXIT

cd "$TMP"

# Workaround for tmp Windows paths ending with "~1" in bash emulation
git init workaround
cd workaround
TMP="$(dirname "$(git rev-parse --show-toplevel)")"
cd "$TMP"
rm -rf workaround

git init --bare child-bare
git init --bare other-bare
git clone child-bare child
cd child
echo a >> a
git add -A
git commit -m created
echo b >> a
git add -A
git commit -m changed
git push ../child-bare master
git push ../other-bare master
CHILDREV="$(git rev-parse HEAD)"

cd "$TMP"
git init parent

config() {
  git config --file "$1" "$2"
}

log-message() {
  git log -1 --pretty=format:%s "${1:-HEAD}"
}

cd "$TMP/parent"

# Test export
mkdir module
echo f > module/f
git add -A
git commit -m module
git init --bare "$TMP/module-bare"
git srepo export module "$TMP/module-bare"
git clone "$TMP/module-bare" "$TMP/module"
cd "$TMP/module"
fail-if "Export failed" \
  equals "$(cat f)" "f"

cd "$TMP/parent"

# Test import
XPREVHEAD=""
git srepo import x ../child-bare
XCFG="x/.subrepo/config"

check-initial-x() {
  fail-if "log message incorrect" \
    equals "$(log-message)" "Imported x from ../child-bare"

  fail-if "x files are different" diff -w x/a ../child/a

  fail-if "x remoterev is incorrect" \
    equals "$(config "$XCFG" subrepo.remoterev)" "$CHILDREV"
}
check-initial-x

# Ensure pull doesn't change anything
YPREVHEAD="$(git rev-parse HEAD)"
git srepo pull x
fail-if "pull x has changed something" equals "$(git rev-parse HEAD)" "$YPREVHEAD"
check-initial-x

git srepo import s/y ../other-bare
YCFG="s/y/.subrepo/config"

fail-if "log message incorrect" \
  equals "$(log-message)" "Imported s/y from ../other-bare"

fail-if "y files are different" diff -w s/y/a ../child/a

fail-if "y remoterev is incorrect" \
  equals "$(config "$YCFG" subrepo.remoterev)" "$CHILDREV"

cd "$TMP/child"
echo b >> a
git add -A
git commit -m more
git push
NEWCHILDREV="$(git rev-parse HEAD)"

cd "$TMP/parent"
XPREVHEAD="$(git rev-parse HEAD)"
git srepo pull x

check-changed-x() {
  fail-if "log message incorrect" \
    equals "$(log-message)" "Updated x from ../child-bare"

  fail-if "x files are different" diff -w x/a ../child/a

  fail-if "x remoterev is incorrect" \
    equals "$(config "$XCFG" subrepo.remoterev)" "$NEWCHILDREV"
}
check-changed-x
PREVHEAD="$(git rev-parse HEAD)"
git srepo pull x
fail-if "second pull x has changed something" \
  equals "$(git rev-parse HEAD)" "$PREVHEAD"
check-changed-x

# Test for unrelated pull not changing anything
git srepo pull s/y
fail-if "second pull y has changed something" \
  equals "$(git rev-parse HEAD)" "$PREVHEAD"

echo "All tests passed"
